### ISSUE TITLE
.invite.me

### ISSUE THREAD

**Issue by fantasy1114** [github-craftwork/start-here#283] opened 2022-09-02 01:39 UTC
I want to access this organization.

**Comment by TanvirOnGH** [comment] 2023-09-03 09:50
@fantasy1114 Hi, Please follow this: https://github.com/github-craftwork/start-here/issues/100

**Comment by TanvirOnGH** [comment] 2023-09-03 09:53
Duplicate of #282

**Closed by TanvirOnGH** 2023-09-03 09:53 UTC
